export * from './building.dto';
export * from './navigation.dto';
export * from './registration.dto';
export * from './shopping.dto';
export * from './cafeteria.dto';
export * from './hall.dto';
export * from './parking.dto';
export * from './lab.dto';
export * from './office.dto';
export * from './parking.dto';
export * from './shopping.dto';
export * from './class.dto';
export * from './dormitory.dto';
export * from './departement.dto';
export * from './science-type.dto'
export * from './adminstrative-unit.dto'
export * from './filter.dto'
export * from './college.dto'
